version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - depguard
    - govet
    - ineffassign
    - staticcheck
    - unused

  settings:
    depguard:
      rules:
        main:
          list-mode: lax
          deny:
            - pkg: "log$"
              desc: "Use log/slog instead of the standard log package"
