// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"
)

type Message struct {
	ID              string         `json:"id"`
	Room            string         `json:"room"`
	User            string         `json:"user"`
	Content         string         `json:"content"`
	Timestamp       time.Time      `json:"timestamp"`
	Signature       sql.NullString `json:"signature"`
	Pubkey          sql.NullString `json:"pubkey"`
	SignedTimestamp sql.NullInt64  `json:"signed_timestamp"`
}

type User struct {
	PublicKey string    `json:"public_key"`
	Verified  bool      `json:"verified"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
