// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (id, room, user, content, timestamp, signature, pubkey, signed_timestamp)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, room, user, content, timestamp, signature, pubkey, signed_timestamp
`

type CreateMessageParams struct {
	ID              string         `json:"id"`
	Room            string         `json:"room"`
	User            string         `json:"user"`
	Content         string         `json:"content"`
	Timestamp       time.Time      `json:"timestamp"`
	Signature       sql.NullString `json:"signature"`
	Pubkey          sql.NullString `json:"pubkey"`
	SignedTimestamp sql.NullInt64  `json:"signed_timestamp"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, createMessage,
		arg.ID,
		arg.Room,
		arg.User,
		arg.Content,
		arg.Timestamp,
		arg.Signature,
		arg.Pubkey,
		arg.SignedTimestamp,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.Room,
		&i.User,
		&i.Content,
		&i.Timestamp,
		&i.Signature,
		&i.Pubkey,
		&i.SignedTimestamp,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (public_key, verified, created_at, updated_at)
VALUES (?, ?, ?, ?)
RETURNING public_key, verified, created_at, updated_at
`

type CreateUserParams struct {
	PublicKey string    `json:"public_key"`
	Verified  bool      `json:"verified"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.PublicKey,
		arg.Verified,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.PublicKey,
		&i.Verified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT public_key, verified, created_at, updated_at FROM users
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.PublicKey,
			&i.Verified,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessageCountByRoom = `-- name: GetMessageCountByRoom :one
SELECT COUNT(*) as count
FROM messages
WHERE room = ?
`

func (q *Queries) GetMessageCountByRoom(ctx context.Context, room string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getMessageCountByRoom, room)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getMessagesByRoom = `-- name: GetMessagesByRoom :many
SELECT id, room, user, content, timestamp, signature, pubkey, signed_timestamp FROM messages
WHERE room = ?
ORDER BY timestamp ASC
`

func (q *Queries) GetMessagesByRoom(ctx context.Context, room string) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, getMessagesByRoom, room)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.Room,
			&i.User,
			&i.Content,
			&i.Timestamp,
			&i.Signature,
			&i.Pubkey,
			&i.SignedTimestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoomsWithMessageCount = `-- name: GetRoomsWithMessageCount :many
SELECT room, COUNT(*) as message_count
FROM messages
GROUP BY room
`

type GetRoomsWithMessageCountRow struct {
	Room         string `json:"room"`
	MessageCount int64  `json:"message_count"`
}

func (q *Queries) GetRoomsWithMessageCount(ctx context.Context) ([]GetRoomsWithMessageCountRow, error) {
	rows, err := q.db.QueryContext(ctx, getRoomsWithMessageCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRoomsWithMessageCountRow{}
	for rows.Next() {
		var i GetRoomsWithMessageCountRow
		if err := rows.Scan(&i.Room, &i.MessageCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByPublicKey = `-- name: GetUserByPublicKey :one
SELECT public_key, verified, created_at, updated_at FROM users
WHERE public_key = ?
`

func (q *Queries) GetUserByPublicKey(ctx context.Context, publicKey string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByPublicKey, publicKey)
	var i User
	err := row.Scan(
		&i.PublicKey,
		&i.Verified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserVerified = `-- name: GetUserVerified :one
SELECT verified FROM users
WHERE public_key = ?
`

func (q *Queries) GetUserVerified(ctx context.Context, publicKey string) (bool, error) {
	row := q.db.QueryRowContext(ctx, getUserVerified, publicKey)
	var verified bool
	err := row.Scan(&verified)
	return verified, err
}

const updateUserVerified = `-- name: UpdateUserVerified :exec
UPDATE users
SET verified = ?, updated_at = ?
WHERE public_key = ?
`

type UpdateUserVerifiedParams struct {
	Verified  bool      `json:"verified"`
	UpdatedAt time.Time `json:"updated_at"`
	PublicKey string    `json:"public_key"`
}

func (q *Queries) UpdateUserVerified(ctx context.Context, arg UpdateUserVerifiedParams) error {
	_, err := q.db.ExecContext(ctx, updateUserVerified, arg.Verified, arg.UpdatedAt, arg.PublicKey)
	return err
}

const userExistsByPublicKey = `-- name: UserExistsByPublicKey :one
SELECT COUNT(*) > 0 as user_exists FROM users WHERE public_key = ?
`

func (q *Queries) UserExistsByPublicKey(ctx context.Context, publicKey string) (bool, error) {
	row := q.db.QueryRowContext(ctx, userExistsByPublicKey, publicKey)
	var user_exists bool
	err := row.Scan(&user_exists)
	return user_exists, err
}
