// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (id, room, user, content, timestamp, signature, pubkey, signed_timestamp, is_encrypted, nonce)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, room, user, content, timestamp, signature, pubkey, signed_timestamp, is_encrypted, nonce
`

type CreateMessageParams struct {
	ID              string         `json:"id"`
	Room            string         `json:"room"`
	User            string         `json:"user"`
	Content         string         `json:"content"`
	Timestamp       time.Time      `json:"timestamp"`
	Signature       sql.NullString `json:"signature"`
	Pubkey          sql.NullString `json:"pubkey"`
	SignedTimestamp sql.NullInt64  `json:"signed_timestamp"`
	IsEncrypted     sql.NullBool   `json:"is_encrypted"`
	Nonce           sql.NullString `json:"nonce"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, createMessage,
		arg.ID,
		arg.Room,
		arg.User,
		arg.Content,
		arg.Timestamp,
		arg.Signature,
		arg.Pubkey,
		arg.SignedTimestamp,
		arg.IsEncrypted,
		arg.Nonce,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.Room,
		&i.User,
		&i.Content,
		&i.Timestamp,
		&i.Signature,
		&i.Pubkey,
		&i.SignedTimestamp,
		&i.IsEncrypted,
		&i.Nonce,
	)
	return i, err
}

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms (name, password_hash, is_encrypted, encryption_salt, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING name, created_at, updated_at, password_hash, is_encrypted, encryption_salt
`

type CreateRoomParams struct {
	Name           string         `json:"name"`
	PasswordHash   sql.NullString `json:"password_hash"`
	IsEncrypted    sql.NullBool   `json:"is_encrypted"`
	EncryptionSalt sql.NullString `json:"encryption_salt"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error) {
	row := q.db.QueryRowContext(ctx, createRoom,
		arg.Name,
		arg.PasswordHash,
		arg.IsEncrypted,
		arg.EncryptionSalt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Room
	err := row.Scan(
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.IsEncrypted,
		&i.EncryptionSalt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (public_key, verified, created_at, updated_at)
VALUES (?, ?, ?, ?)
RETURNING public_key, verified, created_at, updated_at
`

type CreateUserParams struct {
	PublicKey string    `json:"public_key"`
	Verified  bool      `json:"verified"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.PublicKey,
		arg.Verified,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.PublicKey,
		&i.Verified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT public_key, verified, created_at, updated_at FROM users
LIMIT 100
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.PublicKey,
			&i.Verified,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessageCountByRoom = `-- name: GetMessageCountByRoom :one
SELECT COUNT(*) as count
FROM messages
WHERE room = ?
`

func (q *Queries) GetMessageCountByRoom(ctx context.Context, room string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getMessageCountByRoom, room)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getMessagesByRoom = `-- name: GetMessagesByRoom :many
SELECT id, room, user, content, timestamp, signature, pubkey, signed_timestamp, is_encrypted, nonce FROM messages
WHERE room = ?
ORDER BY timestamp ASC
LIMIT 100
`

func (q *Queries) GetMessagesByRoom(ctx context.Context, room string) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, getMessagesByRoom, room)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.Room,
			&i.User,
			&i.Content,
			&i.Timestamp,
			&i.Signature,
			&i.Pubkey,
			&i.SignedTimestamp,
			&i.IsEncrypted,
			&i.Nonce,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoomByName = `-- name: GetRoomByName :one
SELECT name, created_at, updated_at, password_hash, is_encrypted, encryption_salt FROM rooms
WHERE name = ?
`

func (q *Queries) GetRoomByName(ctx context.Context, name string) (Room, error) {
	row := q.db.QueryRowContext(ctx, getRoomByName, name)
	var i Room
	err := row.Scan(
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.IsEncrypted,
		&i.EncryptionSalt,
	)
	return i, err
}

const getRoomPasswordHash = `-- name: GetRoomPasswordHash :one
SELECT password_hash FROM rooms WHERE name = ?
`

func (q *Queries) GetRoomPasswordHash(ctx context.Context, name string) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getRoomPasswordHash, name)
	var password_hash sql.NullString
	err := row.Scan(&password_hash)
	return password_hash, err
}

const getRoomsWithLasMessage = `-- name: GetRoomsWithLasMessage :many
SELECT
    r.name,
    CASE WHEN r.password_hash IS NOT NULL THEN 1 ELSE 0 END as has_password,
    r.is_encrypted,
    COALESCE(r.encryption_salt, '') as encryption_salt,
    COALESCE(last_msg.content, '') as last_message_content,
    COALESCE(last_msg.user, '') as last_message_user,
    CASE
        WHEN last_msg.timestamp IS NULL THEN CAST('1970-01-01 00:00:00' AS TEXT)
        ELSE CAST(last_msg.timestamp AS TEXT)
    END as last_message_timestamp
FROM rooms r
LEFT JOIN (
    SELECT id, room, user, content, timestamp, signature, pubkey, signed_timestamp, is_encrypted, nonce, rn
    FROM (
        SELECT m.id, m.room, m.user, m.content, m.timestamp, m.signature, m.pubkey, m.signed_timestamp, m.is_encrypted, m.nonce,
               ROW_NUMBER() OVER (PARTITION BY room ORDER BY timestamp DESC) as rn
        FROM messages m
    )
    WHERE rn = 1
) last_msg ON last_msg.room = r.name
ORDER BY last_msg.timestamp DESC, r.name ASC
LIMIT 100
`

type GetRoomsWithLasMessageRow struct {
	Name                 string       `json:"name"`
	HasPassword          int64        `json:"has_password"`
	IsEncrypted          sql.NullBool `json:"is_encrypted"`
	EncryptionSalt       string       `json:"encryption_salt"`
	LastMessageContent   string       `json:"last_message_content"`
	LastMessageUser      string       `json:"last_message_user"`
	LastMessageTimestamp string       `json:"last_message_timestamp"`
}

func (q *Queries) GetRoomsWithLasMessage(ctx context.Context) ([]GetRoomsWithLasMessageRow, error) {
	rows, err := q.db.QueryContext(ctx, getRoomsWithLasMessage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRoomsWithLasMessageRow{}
	for rows.Next() {
		var i GetRoomsWithLasMessageRow
		if err := rows.Scan(
			&i.Name,
			&i.HasPassword,
			&i.IsEncrypted,
			&i.EncryptionSalt,
			&i.LastMessageContent,
			&i.LastMessageUser,
			&i.LastMessageTimestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByPublicKey = `-- name: GetUserByPublicKey :one
SELECT public_key, verified, created_at, updated_at FROM users
WHERE public_key = ?
`

func (q *Queries) GetUserByPublicKey(ctx context.Context, publicKey string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByPublicKey, publicKey)
	var i User
	err := row.Scan(
		&i.PublicKey,
		&i.Verified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserVerified = `-- name: GetUserVerified :one
SELECT verified FROM users
WHERE public_key = ?
`

func (q *Queries) GetUserVerified(ctx context.Context, publicKey string) (bool, error) {
	row := q.db.QueryRowContext(ctx, getUserVerified, publicKey)
	var verified bool
	err := row.Scan(&verified)
	return verified, err
}

const getUserWithPostCount = `-- name: GetUserWithPostCount :one
SELECT
    u.public_key, u.verified, u.created_at, u.updated_at,
    COALESCE((SELECT COUNT(*) FROM messages WHERE pubkey = u.public_key), 0) as post_count
FROM users u
WHERE u.public_key = ?
`

type GetUserWithPostCountRow struct {
	PublicKey string      `json:"public_key"`
	Verified  bool        `json:"verified"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
	PostCount interface{} `json:"post_count"`
}

func (q *Queries) GetUserWithPostCount(ctx context.Context, publicKey string) (GetUserWithPostCountRow, error) {
	row := q.db.QueryRowContext(ctx, getUserWithPostCount, publicKey)
	var i GetUserWithPostCountRow
	err := row.Scan(
		&i.PublicKey,
		&i.Verified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PostCount,
	)
	return i, err
}

const roomExists = `-- name: RoomExists :one
SELECT COUNT(*) > 0 as room_exists FROM rooms WHERE name = ?
`

func (q *Queries) RoomExists(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRowContext(ctx, roomExists, name)
	var room_exists bool
	err := row.Scan(&room_exists)
	return room_exists, err
}

const searchRoomsByName = `-- name: SearchRoomsByName :many
SELECT
    r.name,
    CASE WHEN r.password_hash IS NOT NULL THEN 1 ELSE 0 END as has_password,
    r.is_encrypted,
    COALESCE(r.encryption_salt, '') as encryption_salt,
    COALESCE(last_msg.content, '') as last_message_content,
    COALESCE(last_msg.user, '') as last_message_user,
    CASE
        WHEN last_msg.timestamp IS NULL THEN CAST('1970-01-01 00:00:00' AS TEXT)
        ELSE CAST(last_msg.timestamp AS TEXT)
    END as last_message_timestamp
FROM rooms r
LEFT JOIN (
    SELECT id, room, user, content, timestamp, signature, pubkey, signed_timestamp, is_encrypted, nonce, rn
    FROM (
        SELECT m.id, m.room, m.user, m.content, m.timestamp, m.signature, m.pubkey, m.signed_timestamp, m.is_encrypted, m.nonce,
               ROW_NUMBER() OVER (PARTITION BY room ORDER BY timestamp DESC) as rn
        FROM messages m
    )
    WHERE rn = 1
) last_msg ON last_msg.room = r.name
WHERE r.name LIKE '%' || ? || '%'
ORDER BY last_message_timestamp DESC, r.name ASC
LIMIT 100
`

type SearchRoomsByNameRow struct {
	Name                 string       `json:"name"`
	HasPassword          int64        `json:"has_password"`
	IsEncrypted          sql.NullBool `json:"is_encrypted"`
	EncryptionSalt       string       `json:"encryption_salt"`
	LastMessageContent   string       `json:"last_message_content"`
	LastMessageUser      string       `json:"last_message_user"`
	LastMessageTimestamp string       `json:"last_message_timestamp"`
}

func (q *Queries) SearchRoomsByName(ctx context.Context, dollar_1 sql.NullString) ([]SearchRoomsByNameRow, error) {
	rows, err := q.db.QueryContext(ctx, searchRoomsByName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchRoomsByNameRow{}
	for rows.Next() {
		var i SearchRoomsByNameRow
		if err := rows.Scan(
			&i.Name,
			&i.HasPassword,
			&i.IsEncrypted,
			&i.EncryptionSalt,
			&i.LastMessageContent,
			&i.LastMessageUser,
			&i.LastMessageTimestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserVerified = `-- name: UpdateUserVerified :exec
UPDATE users
SET verified = ?, updated_at = ?
WHERE public_key = ?
`

type UpdateUserVerifiedParams struct {
	Verified  bool      `json:"verified"`
	UpdatedAt time.Time `json:"updated_at"`
	PublicKey string    `json:"public_key"`
}

func (q *Queries) UpdateUserVerified(ctx context.Context, arg UpdateUserVerifiedParams) error {
	_, err := q.db.ExecContext(ctx, updateUserVerified, arg.Verified, arg.UpdatedAt, arg.PublicKey)
	return err
}

const userExistsByPublicKey = `-- name: UserExistsByPublicKey :one
SELECT COUNT(*) > 0 as user_exists FROM users WHERE public_key = ?
`

func (q *Queries) UserExistsByPublicKey(ctx context.Context, publicKey string) (bool, error) {
	row := q.db.QueryRowContext(ctx, userExistsByPublicKey, publicKey)
	var user_exists bool
	err := row.Scan(&user_exists)
	return user_exists, err
}
