// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (id, room, user, content, timestamp, signature, pubkey, signed_timestamp)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, room, user, content, timestamp, signature, pubkey, signed_timestamp
`

type CreateMessageParams struct {
	ID              string         `json:"id"`
	Room            string         `json:"room"`
	User            string         `json:"user"`
	Content         string         `json:"content"`
	Timestamp       time.Time      `json:"timestamp"`
	Signature       sql.NullString `json:"signature"`
	Pubkey          sql.NullString `json:"pubkey"`
	SignedTimestamp sql.NullInt64  `json:"signed_timestamp"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, createMessage,
		arg.ID,
		arg.Room,
		arg.User,
		arg.Content,
		arg.Timestamp,
		arg.Signature,
		arg.Pubkey,
		arg.SignedTimestamp,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.Room,
		&i.User,
		&i.Content,
		&i.Timestamp,
		&i.Signature,
		&i.Pubkey,
		&i.SignedTimestamp,
	)
	return i, err
}

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms (name, hidden, created_at, updated_at)
VALUES (?, ?, ?, ?)
RETURNING name, hidden, created_at, updated_at
`

type CreateRoomParams struct {
	Name      string    `json:"name"`
	Hidden    bool      `json:"hidden"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error) {
	row := q.db.QueryRowContext(ctx, createRoom,
		arg.Name,
		arg.Hidden,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Room
	err := row.Scan(
		&i.Name,
		&i.Hidden,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (public_key, verified, created_at, updated_at)
VALUES (?, ?, ?, ?)
RETURNING public_key, verified, created_at, updated_at
`

type CreateUserParams struct {
	PublicKey string    `json:"public_key"`
	Verified  bool      `json:"verified"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.PublicKey,
		arg.Verified,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.PublicKey,
		&i.Verified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT public_key, verified, created_at, updated_at FROM users
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.PublicKey,
			&i.Verified,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessageCountByRoom = `-- name: GetMessageCountByRoom :one
SELECT COUNT(*) as count
FROM messages
WHERE room = ?
`

func (q *Queries) GetMessageCountByRoom(ctx context.Context, room string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getMessageCountByRoom, room)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getMessagesByRoom = `-- name: GetMessagesByRoom :many
SELECT id, room, user, content, timestamp, signature, pubkey, signed_timestamp FROM messages
WHERE room = ?
ORDER BY timestamp ASC
`

func (q *Queries) GetMessagesByRoom(ctx context.Context, room string) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, getMessagesByRoom, room)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.Room,
			&i.User,
			&i.Content,
			&i.Timestamp,
			&i.Signature,
			&i.Pubkey,
			&i.SignedTimestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoomByName = `-- name: GetRoomByName :one
SELECT name, hidden, created_at, updated_at FROM rooms
WHERE name = ?
`

func (q *Queries) GetRoomByName(ctx context.Context, name string) (Room, error) {
	row := q.db.QueryRowContext(ctx, getRoomByName, name)
	var i Room
	err := row.Scan(
		&i.Name,
		&i.Hidden,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoomsWithMessageCount = `-- name: GetRoomsWithMessageCount :many
SELECT
    r.name,
    r.hidden,
    COALESCE((SELECT COUNT(*) FROM messages WHERE room = r.name), 0) as message_count
FROM rooms r
ORDER BY r.name
`

type GetRoomsWithMessageCountRow struct {
	Name         string      `json:"name"`
	Hidden       bool        `json:"hidden"`
	MessageCount interface{} `json:"message_count"`
}

func (q *Queries) GetRoomsWithMessageCount(ctx context.Context) ([]GetRoomsWithMessageCountRow, error) {
	rows, err := q.db.QueryContext(ctx, getRoomsWithMessageCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRoomsWithMessageCountRow{}
	for rows.Next() {
		var i GetRoomsWithMessageCountRow
		if err := rows.Scan(&i.Name, &i.Hidden, &i.MessageCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByPublicKey = `-- name: GetUserByPublicKey :one
SELECT public_key, verified, created_at, updated_at FROM users
WHERE public_key = ?
`

func (q *Queries) GetUserByPublicKey(ctx context.Context, publicKey string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByPublicKey, publicKey)
	var i User
	err := row.Scan(
		&i.PublicKey,
		&i.Verified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserVerified = `-- name: GetUserVerified :one
SELECT verified FROM users
WHERE public_key = ?
`

func (q *Queries) GetUserVerified(ctx context.Context, publicKey string) (bool, error) {
	row := q.db.QueryRowContext(ctx, getUserVerified, publicKey)
	var verified bool
	err := row.Scan(&verified)
	return verified, err
}

const getUserWithPostCount = `-- name: GetUserWithPostCount :one
SELECT
    u.public_key, u.verified, u.created_at, u.updated_at,
    COALESCE((SELECT COUNT(*) FROM messages WHERE pubkey = u.public_key), 0) as post_count
FROM users u
WHERE u.public_key = ?
`

type GetUserWithPostCountRow struct {
	PublicKey string      `json:"public_key"`
	Verified  bool        `json:"verified"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
	PostCount interface{} `json:"post_count"`
}

func (q *Queries) GetUserWithPostCount(ctx context.Context, publicKey string) (GetUserWithPostCountRow, error) {
	row := q.db.QueryRowContext(ctx, getUserWithPostCount, publicKey)
	var i GetUserWithPostCountRow
	err := row.Scan(
		&i.PublicKey,
		&i.Verified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PostCount,
	)
	return i, err
}

const roomExists = `-- name: RoomExists :one
SELECT COUNT(*) > 0 as room_exists FROM rooms WHERE name = ?
`

func (q *Queries) RoomExists(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRowContext(ctx, roomExists, name)
	var room_exists bool
	err := row.Scan(&room_exists)
	return room_exists, err
}

const updateRoomVisibility = `-- name: UpdateRoomVisibility :exec
UPDATE rooms
SET hidden = ?, updated_at = ?
WHERE name = ?
`

type UpdateRoomVisibilityParams struct {
	Hidden    bool      `json:"hidden"`
	UpdatedAt time.Time `json:"updated_at"`
	Name      string    `json:"name"`
}

func (q *Queries) UpdateRoomVisibility(ctx context.Context, arg UpdateRoomVisibilityParams) error {
	_, err := q.db.ExecContext(ctx, updateRoomVisibility, arg.Hidden, arg.UpdatedAt, arg.Name)
	return err
}

const updateUserVerified = `-- name: UpdateUserVerified :exec
UPDATE users
SET verified = ?, updated_at = ?
WHERE public_key = ?
`

type UpdateUserVerifiedParams struct {
	Verified  bool      `json:"verified"`
	UpdatedAt time.Time `json:"updated_at"`
	PublicKey string    `json:"public_key"`
}

func (q *Queries) UpdateUserVerified(ctx context.Context, arg UpdateUserVerifiedParams) error {
	_, err := q.db.ExecContext(ctx, updateUserVerified, arg.Verified, arg.UpdatedAt, arg.PublicKey)
	return err
}

const userExistsByPublicKey = `-- name: UserExistsByPublicKey :one
SELECT COUNT(*) > 0 as user_exists FROM users WHERE public_key = ?
`

func (q *Queries) UserExistsByPublicKey(ctx context.Context, publicKey string) (bool, error) {
	row := q.db.QueryRowContext(ctx, userExistsByPublicKey, publicKey)
	var user_exists bool
	err := row.Scan(&user_exists)
	return user_exists, err
}
