package tui

import (
	"fmt"
	"strings"

	tea "charm.land/bubbletea/v2"
)

type identitiesState int

const (
	identitiesStateList    identitiesState = iota
	identitiesStateAddKey                  // sub-model (identityModel in add mode) active
	identitiesStateAddName                 // typing name after key was generated
)

type identitiesModel struct {
	state         identitiesState
	entries       []identityEntry
	activeIndex   int
	cursor        int
	sub           identityModel // used in addKey state
	pendingKey    identity      // key generated by sub, waiting for name
	inputName     string
	err           string
	configChanged bool
}

func newIdentitiesModel(cfg appConfig) identitiesModel {
	return identitiesModel{entries: cfg.Identities, activeIndex: cfg.ActiveIndex}
}

func (m identitiesModel) update(msg tea.Msg) (identitiesModel, tea.Cmd) {
	switch m.state {
	case identitiesStateList:
		km, ok := msg.(tea.KeyMsg)
		if !ok {
			return m, nil
		}
		switch km.String() {
		case "up", "k":
			if m.cursor > 0 {
				m.cursor--
			}
		case "down", "j":
			if m.cursor < len(m.entries)-1 {
				m.cursor++
			}
		case "enter":
			m.activeIndex = m.cursor
			m.configChanged = true
		case "a":
			m.state = identitiesStateAddKey
			m.sub = newIdentityModelAdd()
		case "d":
			if len(m.entries) > 1 {
				m.entries = append(m.entries[:m.cursor], m.entries[m.cursor+1:]...)
				if m.cursor >= len(m.entries) {
					m.cursor = len(m.entries) - 1
				}
				if m.activeIndex >= len(m.entries) {
					m.activeIndex = len(m.entries) - 1
				} else if m.cursor < m.activeIndex {
					m.activeIndex--
				}
				m.configChanged = true
			}
		case "esc":
			return m, func() tea.Msg { return navigateMsg{to: screenRooms} }
		case "tab":
			return m, func() tea.Msg { return navigateMsg{to: screenContacts} }
		case "ctrl+c", "q":
			return m, tea.Quit
		}

	case identitiesStateAddKey:
		// Intercept esc at menu level to cancel add
		if km, ok := msg.(tea.KeyMsg); ok && km.String() == "esc" && m.sub.state == idStateMenu {
			m.state = identitiesStateList
			return m, nil
		}
		// Handle completion
		if crm, ok := msg.(identityCreatedMsg); ok {
			m.pendingKey = crm.id
			m.state = identitiesStateAddName
			m.inputName = ""
			return m, nil
		}
		// Delegate everything else to sub
		var cmd tea.Cmd
		m.sub, cmd = m.sub.update(msg)
		return m, cmd

	case identitiesStateAddName:
		km, ok := msg.(tea.KeyMsg)
		if !ok {
			return m, nil
		}
		switch km.String() {
		case "enter":
			m.entries = append(m.entries, identityEntry{
				Name:       m.inputName,
				PrivateKey: m.pendingKey.PrivKeyHex,
				PublicKey:  m.pendingKey.PubKeyHex,
			})
			m.configChanged = true
			m.state = identitiesStateList
			m.cursor = len(m.entries) - 1
			m.inputName = ""
		case "backspace":
			if len(m.inputName) > 0 {
				m.inputName = m.inputName[:len(m.inputName)-1]
			}
		case "esc":
			m.state = identitiesStateList
			m.inputName = ""
		case "ctrl+c":
			return m, tea.Quit
		default:
			s := km.String()
			if len(s) == 1 {
				m.inputName += s
			}
		}
	}
	return m, nil
}

func (m identitiesModel) view(width, height int) string {
	var b strings.Builder
	pad := "  "

	b.WriteString("\n\n")
	b.WriteString(pad + "µchat — Identities\n\n")

	switch m.state {
	case identitiesStateList:
		if len(m.entries) == 0 {
			b.WriteString(pad + "(no identities)\n")
		} else {
			for i, e := range m.entries {
				cursor := "  "
				if i == m.cursor {
					cursor = "▶ "
				}
				active := " "
				if i == m.activeIndex {
					active = "*"
				}
				r, g, bv := pubkeyColor(e.PublicKey)
				var nameStr string
				if e.Name != "" {
					nameStr = ansiColor(e.Name, r, g, bv) + "  "
				}
				displayKey := e.PublicKey
				if npub, err := pubKeyHexToNpub(e.PublicKey); err == nil {
					displayKey = npub
				}
				fmt.Fprintf(&b, "%s%s%s %s%s\n", pad, cursor, active, nameStr, formatKeyFull(displayKey))
			}
		}
		b.WriteString("\n")
		b.WriteString(helpBar("↑↓", "navigate", "enter", "activate", "a", "add", "d", "delete", "tab", "contacts", "esc", "rooms", "q", "quit") + "\n")

	case identitiesStateAddKey:
		b.WriteString(m.sub.view(width, height))

	case identitiesStateAddName:
		b.WriteString(pad + "Name this identity (optional):\n\n")
		b.WriteString(pad + "> " + m.inputName + "█\n\n")
		b.WriteString(helpBar("enter", "confirm", "esc", "cancel") + "\n")
	}

	if m.err != "" {
		b.WriteString("\n" + pad + "Error: " + m.err + "\n")
	}

	return b.String()
}
