/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as UserPubkeyRouteImport } from './routes/user.$pubkey'
import { Route as SettingsUserRouteImport } from './routes/settings/user'
import { Route as SettingsServersRouteImport } from './routes/settings/servers'
import { Route as SettingsImportRouteImport } from './routes/settings/import'
import { Route as SettingsIdentitiesRouteImport } from './routes/settings/identities'
import { Route as SettingsExportRouteImport } from './routes/settings/export'
import { Route as SettingsContactsRouteImport } from './routes/settings/contacts'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as ChatRoomNameRouteImport } from './routes/chat.$roomName'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const UserPubkeyRoute = UserPubkeyRouteImport.update({
  id: '/user/$pubkey',
  path: '/user/$pubkey',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsUserRoute = SettingsUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsServersRoute = SettingsServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsImportRoute = SettingsImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsIdentitiesRoute = SettingsIdentitiesRouteImport.update({
  id: '/identities',
  path: '/identities',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsExportRoute = SettingsExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsContactsRoute = SettingsContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => SettingsRoute,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoomNameRoute = ChatRoomNameRouteImport.update({
  id: '/chat/$roomName',
  path: '/chat/$roomName',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteWithChildren
  '/chat/$roomName': typeof ChatRoomNameRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/settings/contacts': typeof SettingsContactsRoute
  '/settings/export': typeof SettingsExportRoute
  '/settings/identities': typeof SettingsIdentitiesRoute
  '/settings/import': typeof SettingsImportRoute
  '/settings/servers': typeof SettingsServersRoute
  '/settings/user': typeof SettingsUserRoute
  '/user/$pubkey': typeof UserPubkeyRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat/$roomName': typeof ChatRoomNameRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/settings/contacts': typeof SettingsContactsRoute
  '/settings/export': typeof SettingsExportRoute
  '/settings/identities': typeof SettingsIdentitiesRoute
  '/settings/import': typeof SettingsImportRoute
  '/settings/servers': typeof SettingsServersRoute
  '/settings/user': typeof SettingsUserRoute
  '/user/$pubkey': typeof UserPubkeyRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteWithChildren
  '/chat/$roomName': typeof ChatRoomNameRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/settings/contacts': typeof SettingsContactsRoute
  '/settings/export': typeof SettingsExportRoute
  '/settings/identities': typeof SettingsIdentitiesRoute
  '/settings/import': typeof SettingsImportRoute
  '/settings/servers': typeof SettingsServersRoute
  '/settings/user': typeof SettingsUserRoute
  '/user/$pubkey': typeof UserPubkeyRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/chat/$roomName'
    | '/demo/tanstack-query'
    | '/settings/contacts'
    | '/settings/export'
    | '/settings/identities'
    | '/settings/import'
    | '/settings/servers'
    | '/settings/user'
    | '/user/$pubkey'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat/$roomName'
    | '/demo/tanstack-query'
    | '/settings/contacts'
    | '/settings/export'
    | '/settings/identities'
    | '/settings/import'
    | '/settings/servers'
    | '/settings/user'
    | '/user/$pubkey'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/chat/$roomName'
    | '/demo/tanstack-query'
    | '/settings/contacts'
    | '/settings/export'
    | '/settings/identities'
    | '/settings/import'
    | '/settings/servers'
    | '/settings/user'
    | '/user/$pubkey'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  ChatRoomNameRoute: typeof ChatRoomNameRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  UserPubkeyRoute: typeof UserPubkeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/user/$pubkey': {
      id: '/user/$pubkey'
      path: '/user/$pubkey'
      fullPath: '/user/$pubkey'
      preLoaderRoute: typeof UserPubkeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/user': {
      id: '/settings/user'
      path: '/user'
      fullPath: '/settings/user'
      preLoaderRoute: typeof SettingsUserRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/servers': {
      id: '/settings/servers'
      path: '/servers'
      fullPath: '/settings/servers'
      preLoaderRoute: typeof SettingsServersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/import': {
      id: '/settings/import'
      path: '/import'
      fullPath: '/settings/import'
      preLoaderRoute: typeof SettingsImportRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/identities': {
      id: '/settings/identities'
      path: '/identities'
      fullPath: '/settings/identities'
      preLoaderRoute: typeof SettingsIdentitiesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/export': {
      id: '/settings/export'
      path: '/export'
      fullPath: '/settings/export'
      preLoaderRoute: typeof SettingsExportRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/contacts': {
      id: '/settings/contacts'
      path: '/contacts'
      fullPath: '/settings/contacts'
      preLoaderRoute: typeof SettingsContactsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$roomName': {
      id: '/chat/$roomName'
      path: '/chat/$roomName'
      fullPath: '/chat/$roomName'
      preLoaderRoute: typeof ChatRoomNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteChildren {
  SettingsContactsRoute: typeof SettingsContactsRoute
  SettingsExportRoute: typeof SettingsExportRoute
  SettingsIdentitiesRoute: typeof SettingsIdentitiesRoute
  SettingsImportRoute: typeof SettingsImportRoute
  SettingsServersRoute: typeof SettingsServersRoute
  SettingsUserRoute: typeof SettingsUserRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsContactsRoute: SettingsContactsRoute,
  SettingsExportRoute: SettingsExportRoute,
  SettingsIdentitiesRoute: SettingsIdentitiesRoute,
  SettingsImportRoute: SettingsImportRoute,
  SettingsServersRoute: SettingsServersRoute,
  SettingsUserRoute: SettingsUserRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRouteWithChildren,
  ChatRoomNameRoute: ChatRoomNameRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  UserPubkeyRoute: UserPubkeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
