/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserPubkeyRouteImport } from './routes/user.$pubkey'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as ChatRoomNameRouteImport } from './routes/chat.$roomName'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsUserRouteImport } from './routes/settings/user'
import { Route as SettingsImportRouteImport } from './routes/settings/import'
import { Route as SettingsExportRouteImport } from './routes/settings/export'
import { Route as SettingsServersRouteImport } from './routes/settings/servers'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserPubkeyRoute = UserPubkeyRouteImport.update({
  id: '/user/$pubkey',
  path: '/user/$pubkey',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoomNameRoute = ChatRoomNameRouteImport.update({
  id: '/chat/$roomName',
  path: '/chat/$roomName',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsUserRoute = SettingsUserRouteImport.update({
  id: '/settings/user',
  path: '/user',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsImportRoute = SettingsImportRouteImport.update({
  id: '/settings/import',
  path: '/import',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsExportRoute = SettingsExportRouteImport.update({
  id: '/settings/export',
  path: '/export',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsServersRoute = SettingsServersRouteImport.update({
  id: '/settings/servers',
  path: '/servers',
  getParentRoute: () => SettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/settings/': typeof SettingsIndexRoute
  '/settings/user': typeof SettingsUserRoute
  '/settings/import': typeof SettingsImportRoute
  '/settings/export': typeof SettingsExportRoute
  '/settings/servers': typeof SettingsServersRoute
  '/chat/$roomName': typeof ChatRoomNameRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/user/$pubkey': typeof UserPubkeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/settings/': typeof SettingsIndexRoute
  '/settings/user': typeof SettingsUserRoute
  '/settings/import': typeof SettingsImportRoute
  '/settings/export': typeof SettingsExportRoute
  '/settings/servers': typeof SettingsServersRoute
  '/chat/$roomName': typeof ChatRoomNameRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/user/$pubkey': typeof UserPubkeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/settings/': typeof SettingsIndexRoute
  '/settings/user': typeof SettingsUserRoute
  '/settings/import': typeof SettingsImportRoute
  '/settings/export': typeof SettingsExportRoute
  '/settings/servers': typeof SettingsServersRoute
  '/chat/$roomName': typeof ChatRoomNameRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/user/$pubkey': typeof UserPubkeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/settings/'
    | '/settings/user'
    | '/settings/import'
    | '/settings/export'
    | '/settings/servers'
    | '/chat/$roomName'
    | '/demo/tanstack-query'
    | '/user/$pubkey'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/settings/'
    | '/settings/user'
    | '/settings/import'
    | '/settings/export'
    | '/settings/servers'
    | '/chat/$roomName'
    | '/demo/tanstack-query'
    | '/user/$pubkey'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/settings/'
    | '/settings/user'
    | '/settings/import'
    | '/settings/export'
    | '/settings/servers'
    | '/chat/$roomName'
    | '/demo/tanstack-query'
    | '/user/$pubkey'
  fileRoutesById: FileRoutesById
}
export interface SettingsRouteChildren {
  SettingsIndexRoute: typeof SettingsIndexRoute
  SettingsUserRoute: typeof SettingsUserRoute
  SettingsImportRoute: typeof SettingsImportRoute
  SettingsExportRoute: typeof SettingsExportRoute
  SettingsServersRoute: typeof SettingsServersRoute
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  ChatRoomNameRoute: typeof ChatRoomNameRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  UserPubkeyRoute: typeof UserPubkeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteImport
    }
    '/settings/user': {
      id: '/settings/user'
      path: '/user'
      fullPath: '/settings/user'
      preLoaderRoute: typeof SettingsUserRouteImport
      parentRoute: typeof SettingsRouteImport
    }
    '/settings/import': {
      id: '/settings/import'
      path: '/import'
      fullPath: '/settings/import'
      preLoaderRoute: typeof SettingsImportRouteImport
      parentRoute: typeof SettingsRouteImport
    }
    '/settings/export': {
      id: '/settings/export'
      path: '/export'
      fullPath: '/settings/export'
      preLoaderRoute: typeof SettingsExportRouteImport
      parentRoute: typeof SettingsRouteImport
    }
    '/settings/servers': {
      id: '/settings/servers'
      path: '/servers'
      fullPath: '/settings/servers'
      preLoaderRoute: typeof SettingsServersRouteImport
      parentRoute: typeof SettingsRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$pubkey': {
      id: '/user/$pubkey'
      path: '/user/$pubkey'
      fullPath: '/user/$pubkey'
      preLoaderRoute: typeof UserPubkeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$roomName': {
      id: '/chat/$roomName'
      path: '/chat/$roomName'
      fullPath: '/chat/$roomName'
      preLoaderRoute: typeof ChatRoomNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const settingsRouteChildren: SettingsRouteChildren = {
  SettingsIndexRoute: SettingsIndexRoute,
  SettingsUserRoute: SettingsUserRoute,
  SettingsImportRoute: SettingsImportRoute,
  SettingsExportRoute: SettingsExportRoute,
  SettingsServersRoute: SettingsServersRoute,
}

const SettingsRouteWithChildren =
  SettingsRoute._addFileChildren(settingsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRouteWithChildren,
  ChatRoomNameRoute: ChatRoomNameRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  UserPubkeyRoute: UserPubkeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
