/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserPubkeyRouteImport } from './routes/user.$pubkey'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as ChatRoomNameRouteImport } from './routes/chat.$roomName'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserPubkeyRoute = UserPubkeyRouteImport.update({
  id: '/user/$pubkey',
  path: '/user/$pubkey',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoomNameRoute = ChatRoomNameRouteImport.update({
  id: '/chat/$roomName',
  path: '/chat/$roomName',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/chat/$roomName': typeof ChatRoomNameRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/user/$pubkey': typeof UserPubkeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/chat/$roomName': typeof ChatRoomNameRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/user/$pubkey': typeof UserPubkeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/chat/$roomName': typeof ChatRoomNameRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/user/$pubkey': typeof UserPubkeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/chat/$roomName'
    | '/demo/tanstack-query'
    | '/user/$pubkey'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/chat/$roomName'
    | '/demo/tanstack-query'
    | '/user/$pubkey'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/chat/$roomName'
    | '/demo/tanstack-query'
    | '/user/$pubkey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  ChatRoomNameRoute: typeof ChatRoomNameRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  UserPubkeyRoute: typeof UserPubkeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$pubkey': {
      id: '/user/$pubkey'
      path: '/user/$pubkey'
      fullPath: '/user/$pubkey'
      preLoaderRoute: typeof UserPubkeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$roomName': {
      id: '/chat/$roomName'
      path: '/chat/$roomName'
      fullPath: '/chat/$roomName'
      preLoaderRoute: typeof ChatRoomNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  ChatRoomNameRoute: ChatRoomNameRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  UserPubkeyRoute: UserPubkeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
